### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Add background color
- [x] Add image of car

**Comment by alexei-dayrit** [comment]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [ ] Add background color
- [ ] Add image of car
