### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create data model that includes direction the car is facing.
- [x] Create CSS classes that handles car rotation
- [x] Add keydown events that allow user to rotate the car with arrow keys
